"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-t(*uo_zz!heud#1po*du=f5i0r!v-(e7up7^g_z4g@mk59w$)b"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

LOGGING = {
    "version": 1,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {"rag": {"handlers": ["console"], "level": "DEBUG"}},
}

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    # Project apps
    "accounts",
    "documents",
    "chat",
    "rag",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# this is custom

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

NVIDIA_API_KEY = os.getenv("NVIDIA_API_KEY")
NVIDIA_BASE_URL = os.getenv(
    "NVIDIA_BASE_URL",
    "https://integrate.api.nvidia.com/v1",
)
NVIDIA_CHAT_MODEL = os.getenv("NVIDIA_CHAT_MODEL")
NVIDIA_EMBEDDING_MODEL = os.getenv("NVIDIA_EMBEDDING_MODEL")
NVIDIA_RERANK_MODEL = os.getenv(
    "NVIDIA_RERANK_MODEL",
    "nvidia/rerank-qa-mistral-4b",
)

QDRANT_URL = os.getenv("QDRANT_URL", "http://localhost:6333")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY") or None

QDRANT_COLLECTION_NAME = os.getenv(
    "QDRANT_COLLECTION_NAME",
    "document_chunks_v2",
)


# Chunks handed to the model after reranking.
RAG_TOP_N = 5  # was 6 — one fewer passage, slightly smaller prompt

# How many candidates Qdrant returns before reranking.
# Fewer candidates = faster rerank API call.
RAG_SEARCH_CANDIDATES = 16  # was 24 (hardcoded) — now configurable

# Calibrated on evaluation data. Recalibrate if the reranker model or corpus changes.
RAG_RERANK_FLOOR = -11.0

# Query understanding. Regex always runs; this only enables LLM fallback.
RAG_ENABLE_LLM_INTENT = True
RAG_INTENT_MAX_TOKENS = 60  # was 80 — JSON output needs fewer tokens
RAG_INTENT_TIMEOUT = 5  # was 10 — fail fast, fallback handles it

# Overview uses opening chunks from indexed documents instead of topic search.
RAG_OVERVIEW_MAX_DOCUMENTS = 4  # was 5
RAG_OVERVIEW_DOC_CHUNKS = 3

# Conversation memory. The session keeps more than the model sees: storing a
# message is free, sending one is prompt on every call.
RAG_HISTORY_LIMIT = 10  # was 20 — fewer turns = smaller prompt = faster
RAG_HISTORY_STORE_LIMIT = 40  # messages kept in the session (unchanged)
RAG_HISTORY_CHAR_BUDGET = 3000  # was 6000 — tighter budget, less prompt bloat
RAG_HISTORY_MESSAGE_CHARS = 500  # was 700 — clip older messages harder
RAG_INTENT_HISTORY_MESSAGES = 4  # was 6 — classifier needs less context
